$root_path = "../.."
$node_modules = "#{$root_path}/node_modules"
$react_native_path = "#{$node_modules}/react-native"

require_relative "#{$node_modules}/react-native/scripts/react_native_pods"
require_relative "#{$node_modules}/@react-native-community/cli-platform-ios/native_modules"

platform :ios, "10.0"

target 'RNFBSDKExample' do
  use_react_native!(path: $react_native_path)

  pod 'react-native-fbsdk', :path => '../../'
end
